services:
  webapp:
    container_name: webapp
    build: ./webapp
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NEXT_PUBLIC_FINANCIAL_MODELING_PREP_ENDPOINT=${FINANCIAL_MODELING_PREP_ENDPOINT}
      - NEXT_PUBLIC_FINANCIAL_MODELING_PREP_API_KEY=${FINANCIAL_MODELING_PREP_API_KEY}
      - NEXT_PUBLIC_FIREBASE_API_KEY=${FIREBASE_API_KEY}
      - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN}
      - NEXT_PUBLIC_FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}
      - NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID}
      - NEXT_PUBLIC_FIREBASE_APP_ID=${FIREBASE_APP_ID}
    ports:
      - 3000:3000
    volumes:
      - ./webapp:/app
      - /app/node_modules
