services:
  webapp:
    container_name: webapp
    build: ./webapp
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NEXT_PUBLIC_FINANCIAL_MODELING_PREP_ENDPOINT=${FINANCIAL_MODELING_PREP_ENDPOINT}
      - NEXT_PUBLIC_FINANCIAL_MODELING_PREP_API_KEY=${FINANCIAL_MODELING_PREP_API_KEY}
    ports:
      - 3000:3000
    volumes:
      - ./webapp:/app
      - /app/node_modules
